### PR TITLE
upgrade envinfo to 4.3.1

### PR DESCRIPTION
**Pull request by tabrindle**
Envinfo needed to output a commonjs bundle to be imported this way. In the future I might make a selection of different bundles. 

I also needed to add a main entry in package.js, and have two entries in the dist/ folder - one for the main library and one for the cli. 

While I was at it, I got rid of the extra import we had in report, and just used envinfo from context.

### CODE REVIEW

**Comment by tabrindle** [comment]
Im such an idiot, don't merge this yet.

**Comment by GantMan** [comment]
Hahahah ok.  BTW, I should be grabbing helpers off of context now.  That way I only have to change it in one spot.

**Comment by GantMan** [comment]
Do you have to change the name of `.envInfo` to `.envInfoHelpers`?  I think it's best to keep the name bc theres 1 plugin that expects it to be named that.

**Comment by tabrindle** [comment]
Don't have to - but per discussion let's save making casing consistent until another time when we make a breaking change. It's mostly just preference. ¯\_(ツ)_/¯

**Pull request merged**
