### PR TITLE
Solidarity Report => envinfo

### PR DESCRIPTION
**Pull request by tabrindle**
Use envinfo package to print diagnostic info.

### CODE REVIEW

**Comment by GantMan** [comment]
Not sure why CI is failing here.  Seems to be a network issue.

**Comment by GantMan** [comment]
Hey bud, can you add a basic test?  I wanna keep coverage over 75% :)

**Comment by GantMan** [comment]
Hey @tabrindle - tested this on a folder that doesn't have a package.json and it looks like it does a no-op.   I guess bc duplicates and packages are turned on by default.

I think one thing, that is key, is that I utilize those awesome functions you have.  Maybe even expose your module as a feature set.

Would you be interested in doing a meeting to discuss?  I have an AWESOME idea on how to integrate everything.

**Comment by tabrindle** [comment]
Just for transparency: fixed no-op, and have exposed functions in a recent push 👍

**Pull request merged**
