### PR TITLE
Support ~ in path with resolve-dir

### PR DESCRIPTION
**Pull request by piecioshka**

### CODE REVIEW

**Comment by GantMan** [comment]
Sorry for the delay, can you see about updating the tests to pass?

**Comment by piecioshka** [comment]
@GantMan Sorry for my delay. Everything should works.

I can't see that tests on Semaphore CI work, but on Travis is occur a problem with running them.

**Comment by GantMan** [comment]
@piecioshka - please resolve the conflict and tests should pass.

**Comment by piecioshka** [comment]
@GantMan Done. 

Do you know what happen on Travis?

**Comment by GantMan** [comment]
No I do not.  It has this error:  
image

I'm gonna re-run it.

**Comment by tabrindle** [comment]
if you have that error, its because yarn has to update its lockfile, but --frozen-lockfile prevents it from doing so. A good idea on ci. The fix is simple - rerun yarn locally, and push the changes to the lockfile. Which makes sense here because the package.json was changed, and with no changes to yarn.lock

**Comment by GantMan** [comment]
@piecioshka - once this is merged, I'll release a new version.

**Comment by piecioshka** [comment]
Hi @GantMan!

I updated yarn.lock file (what @tabrindle told).
We cannot merge this PR because we have a problem with a new service that is used — `codecov/patch`

How can we resolve that issue?

**Comment by GantMan** [comment]
merged!

**Pull request merged**
