### PR TITLE
add license in your readme file

### PR DESCRIPTION
**Pull request by jokosu10**

### CODE REVIEW

**Comment by GantMan** [comment]
I know I'm being picky, but do you mind moving this under "Additional Info" ?  I think giving it an entire section is kinda too much.  Maybe something like this:

```md
## Additional Info
### License
The MIT License (MIT). Please see [License File](LICENSE.md) for more information.

### NPM Details
[![NPM](https://nodei.co/npm/solidarity.png)](https://npmjs.org/package/solidarity)
```

**Comment by GantMan** [comment]
nm, I'm gonna merge this and then do that small touchup myself.

**Comment by jokosu10** [comment]
thanks for merged my pull request

**Comment by GantMan** [comment]
*high five*

**Pull request merged**
