### PR TITLE
Dist folder - testing and proper building

### PR DESCRIPTION
**Pull request by GantMan**
Found that dist is not tested in integration and worse yet the `templates` folder is not being copied to NPM!

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@GantMan What's the status of this?

**Comment by GantMan** [comment]
I think I had trouble getting it to work on Windows, lots of trouble.

**Comment by GantMan** [comment]
I'm gonna take a look at this once again, and I'll let you know.

**Comment by jamonholmgren** [comment]
Man that TravisBuddy bot is annoying.

**Comment by tabrindle** [comment]
Oh my God yes

**Comment by jamonholmgren** [comment]
@GantMan Can we disable the Travis bot please?

**Pull request merged**
