### PR TITLE
feature: add docsify to repo

### PR DESCRIPTION
**Pull request by rmnegatives**
#Add docsify

- `npm run generate:docs` to generate docs
- `npm run serve:docs` to serve locally on localhost:3000 for dev purposes
- More here ->[docsify cli](https://github.com/QingWei-Li/docsify/blob/master/docs/quickstart.md)

### CODE REVIEW

**Comment by GantMan** [comment]
@rmnegatives - this looks amazing!  I have a few nits and then I'd love to merge.

### #1 Breaks Github Links
I love that I can click on the docs for the website and read them, but changing the link in the markdown means that a developer browsing the readme and clicking the link will now get a 404.  You can see this when you click on any docs links in your branch:  https://github.com/rmnegatives/solidarity/tree/feature/update-docs-for-docsify

### #2 Missing Graphics
Any way missing graphics can be automatically fixed?  I know I can use absolute paths, but I'm hoping there's a simple solution.

### #3 Sidebar back?
Once you click on an item, the only way to return home is to click on the word `solidarity`.  Which took me a minute to realize. Any way to add a link, like "Home"?

**Comment by rmnegatives** [comment]
For Point 3 I noticed this but it seems to be a docsify thing. Ideally it should at least highlight maybe ill make a quick PR to docsify. But thats how that works unfortunately.

**Comment by rmnegatives** [comment]
The graphics thing is really wierd if I put the picture into the docs folder I can path it correctly but ../_art/combo.jpg does not. The only way is relative path [Check this link](https://stackoverflow.com/questions/3655059/html-pick-images-of-root-folder-from-sub-folder)
Im looking into getting the path correct.

**Comment by rmnegatives** [comment]
ugghhh the github thing can be fixed but I might have to take this generate thing out. Seems like the the cli is very basic and does not allow much config. Ill have to maybe make some PR's over there at this point. [Options for cli](https://github.com/QingWei-Li/docsify-cli/blob/a61a0cc5497a3563a2619ddc14c8bdee06c18f64/bin/docsify)

**Comment by GantMan** [comment]
Sounds good.  If you can fix item 1 I think we're good to merge.  Optimizations can happen later 👍 

The docsify docs, seem to have multiple files linked in 1 navigation.

Getting started is a separate scrollable file than customization.  Not sure how they did that.. but it's nice.

**Comment by rmnegatives** [comment]
@GantMan 
after a lot of thought I had to scrap CLI. 
I think ill make a pull request to docsify cli. Its basically useless there is tons of options you can't use.
To test pull down my branch replace -> in docs/index.html
This is best I could do for now to get github logo back and main graphics back.
 homepage: 'https://raw.githubusercontent.com/rmnegatives/solidarity/feature/add-docsify/README.md'.
Its really hard to test the paths without a real server but I think the doc links are right now.
So going forward you can just add options to the index.html like theme color :).
I got the color from the image you named combo it looks way better.

**Comment by rmnegatives** [comment]
Great!

**Pull request merged**
