### PR TITLE
Snapshot update 

### PR DESCRIPTION
**Pull request by mattathompson**
## Work in progress #75 

- [x] Add more specs to test all possible scenarios 
- [ ] Add usage documentation to this PR as well as make updates to the documentation including this new functionality. 
- [x] Self code review.

### CODE REVIEW

**Comment by GantMan** [comment]
Looks like it's broke on windows as of right now.

**Comment by mattathompson** [comment]
@gantman, the appVoyer runner is for windows? That makes much more sense. 

The issue is around the use of the spread operator. I'll look into windows/node limitations.

**Comment by skellock** [comment]
It's a [problem introduced](https://github.com/infinitered/gluegun/issues/285) upstream in `gluegun` with the new table stuff.

Is Appveyor targeting < 8.6 of Node.  If so, then great.  We should have checks like this up on `gluegun`.

**Comment by skellock** [comment]
Ok, I have [PR](https://github.com/infinitered/gluegun/pull/286) in place now.  We'll get this merged in shortly and cut a new build of `gluegun`.

**Comment by mattathompson** [comment]
I also have a place on this PR where I'm using the spread operator. I can make the switch to Object.assign to be safe.

**Comment by mattathompson** [comment]
Thanks for picking that up @skellock

**Comment by GantMan** [comment]
image
^ having trouble actually adding a file rule.

That error message I added to your code, to identify the issue.

**Comment by GantMan** [comment]
Also, looks like it's overwriting and not appending:
image

**Comment by mattathompson** [comment]
Yeah, I saw that when righting more specs this evening. I've got a fix for that but, I'm working through some test failures.

**Comment by GantMan** [comment]
@mattathompson - cool bud!   Let me know when you want me to test again 👍

**Comment by mattathompson** [comment]
Yeah, I haven't had as much time as I'd like to work on opensorce this
week. I'll ping you when it's ready.

**Comment by mattathompson** [comment]
Playing around with the new functionality I've noticed one use case of interest: 

Adding a rule that already exists in the solidarity file... Should we handle that? I built something to handle it w/ cli rules but, would need to extend to all of the other rules.

**Comment by GantMan** [comment]
Just pulled latest, here's my report:

### Clean up the unexpected path experience.
* Forgot to specify specific: I think when someone types 
`solidarity snapshot cli` but forgets to mention the CLI they want, we can just ask with an extra question.  "What's the name of the CLI you'd like to add a rule for?"  
* Forgot to specify rule:  If we get parameters that make no sense like forgetting that they need to specify the rule type -> `solidarity snapshot node` we should give a friendly error. "`node` is not a known solidarity rule.  To add a rule via snapshot you can type `solidarity snapshot <rule> <item>`"

### Duplicates (as you already pointed out)
* Specifying a CLI that already exists:   Adding CLI requirement for Ruby, works first time, I got to add a second time, and I saw `Your new requirement was not added.`
image
* Specifying a PATH/FILE/DIR Rule that already exists:  Just lets me add it twice.  

I think replacing would be best.   

###  New Shell Command
* need a way to add the new shell command provided in #133 

--------------

This PR is starting to really shape up.  Let me know if I can help in any way 👍

**Comment by GantMan** [comment]
Heya @mattathompson - just got back from a biz trip.  Anything I can do to help?

**Comment by mattathompson** [comment]
@GantMan, I'm working on this today. I've addressed all the issues but one so far. Currently right now if you add a duplicate you end up just having two of the same rule. 

Thinking through a solution for that.

**Comment by GantMan** [comment]
Awesome bud.  Let me know if I can help in any way.

**Comment by GantMan** [comment]
Btw I’m presenting this lib at a meetup on the 19th! I’ll be giving you a shoutout

**Comment by mattathompson** [comment]
@GantMan Ready for Review. Need to update the documentation but, this is good to test drive/ code review.

**Comment by mattathompson** [comment]
We've been getting this random failure ^ Not sure what this is about. I've seen it now twice in different tests. Have not seen it locally.

**Comment by GantMan** [comment]
I believe it's a timeout issue.  I can increase the timeout for those tests.  I merged your code with master, will test soon.

**Comment by mattathompson** [comment]
🔥 🔥

**Comment by GantMan** [comment]
- [x] - Test that snapshot still works
- [x] - Test snapshot file without file name requests file name
- [x] - Test file with name does not ask for file name
- [x] - Test add file to existing requirement 
- [x] - Test add file to new requirement
- [x] - Test add cli without name 
- [x] - Test add cli with name
- [x] - Add cli to requirement with existing name
- [x] - Add env rule without name
- [x] - Add environment rule 
- [x] - Add dir rule without name
- [x] - Add dir rule with name
- [x] - Add shell rule without name
- [x] - Add shell rule with name

## Bug
❌   Add  new shell asks for what to match against, but does not add match prop to .solidarity file

## UX issues
❌   Create rule without name but do not type name when prompted (accidental enter issue) result: creates name `undefined` in json
❌   Add  new requirement, but do not type a name  (creates name `undefined` in json)
❌   When adding a shell rule, it says "What is the name of the shell you'd like to add rule for", perhaps here it should say "What is the shell command you'd like to add a rule for"

## Summary
Dude, epic PR!  just a few issues to make it mergable.  Also, do you want to do the docs in this PR or a separate one?  I can help 👍

**Comment by mattathompson** [comment]
Whatever you think is best regarding the documentation! If you want to knock those out I can start on the issues you've raised.

I'm on vacation starting now so I should be able to knock these out pretty quickly. 

Thanks for your review!

**Comment by mattathompson** [comment]
- [ ] Add new shell asks for what to match against, but does not add match prop to .solidarity file

## UX issues
- [ ] Create rule without name but do not type name when prompted (accidental enter issue) result: creates name undefined in json
- [ ] Add new requirement, but do not type a name (creates name undefined in json)
- [ ] When adding a shell rule, it says "What is the name of the shell you'd like to add rule for", perhaps here it should say "What is the shell command you'd like to add a rule for"

**Comment by GantMan** [comment]
Looking good so far!  👍

**Comment by mattathompson** [comment]
@GantMan Baring the test passes on CI all the issues have been addressed.

**Comment by mattathompson** [comment]
@GantMan, Thoughts ^ seems to be happening more frequently after adding a few more tests.

**Comment by GantMan** [comment]
@mattathompson - looks like it might be timout.

We can adjust it like so:  https://github.com/infinitered/solidarity/blob/d55a791bab899ef50f210f0895b430af87b30d5b/__tests__/integration/solidarity-check/check-invalid.ts#L11

Or `jest.setTimeout(10000); // 10 second timeout`

**Comment by GantMan** [comment]
I re-ran tests.  Looks good now!
Also did a quick local test 👍 

Let's do docs in a separate PR - Let me know if you want them or if I should.

**Comment by GantMan** [comment]
# It's ALIVE!!!!

noice

**Comment by mattathompson** [comment]
NOICE! Love me some Jurassic Park.

**Pull request merged**
