### PR TITLE
added dependency check

### PR DESCRIPTION
**Pull request by mohammad-aliB**
as requested in issue #42  i have added a dependency check to show the user a friendly message reminding them to update node

### CODE REVIEW

**Comment by GantMan** [comment]
@mohammad-aliB - it looks like the tests failed on your PR and also I'm not sure I see the `dependenciesMet` function.  So I'm going to accept PR #45 instead, but if you'd like to take a shot at another PR, please let me know on the Github Issue, and I'll reserve and assign it for you.

**Comment by mohammad-aliB** [comment]
@GantMan id like to take another go at it, and ive already made a pull request

**Comment by GantMan** [comment]
@mohammad-aliB - your solution looks good now, but it has a typo now.  I'm just going to merge #45 - 

Let me know if you start another ticket so that no one else completes the same task.  I'm even willing to help you find something easy if you'd like!  Especially considering your existing efforts.

**Comment by mohammad-aliB** [comment]
yeah i spelt "dependencies" wrong, my bad. please let me know if you've got any relatively easy tasks for me to tackle though.

**Comment by GantMan** [comment]
@mohammad-aliB - I highly recommend you take a look at #38 

Basically you'd remove a for loop, and add a way to grab indexes other than first.

**Comment by GantMan** [comment]
@mohammad-aliB - you can probably knock out #48 in < 5 minutes.

**Pull request closed without merging**
