### PR TITLE
fix custom error bug, add test, fix typo, refactor test

### LINKED ISSUE #256: Friendly error not working for dir and file rule type
Version : 3.0.0

Steps :
- Create file or dir type rule with custom friendly error message.

```
{
  "requirements": {
    "TypeScript Active": [
      { "rule": "dir", "location": "./src1", "error": "Did you get this code from npm? Try GitHub!" },
      { "rule": "file", "location": "./1.txt", "error": "You don't have 1.txt. Go get it.!" }
    ]
  }
}
```
- run `solidarity`
- Both rules failed as expected. But doesn't print friendly error message.

Expected : 
Print user specified custom error message from rule.

Used to work in 2.3.1

### PR DESCRIPTION
**Pull request by mishra-ankit**
Fix #256, added test and refactor some tests around custom errors

### CODE REVIEW

**Comment by GantMan** [comment]
Restarting Travis CI

**Comment by GantMan** [comment]
It appears the Danger test is failing.    Can you please comment out https://github.com/infinitered/solidarity/blob/master/.travis.yml#L11

And this will pass.  I'll see about the danger tests later.

**Comment by mishra-ankit** [comment]
@GantMan Commented out for now. Hope it passes this time.

**Comment by mishra-ankit** [comment]
@GantMan Thanks!
Wondering what's the release cycle here ? When can one expect this to be available on npm ?

**Comment by GantMan** [comment]
I believe there's one more PR in the works and we're pushing after that.

https://github.com/infinitered/solidarity/pull/238

**Comment by mishra-ankit** [comment]
Sounds good. Thanks!

**Comment by haakemon** [comment]
@GantMan 
This issue is blocking us from upgrading to version 3. Any chance of a new release with this included?

**Comment by GantMan** [comment]
I just published 3.0.1

**Pull request merged**
